### ISSUE TITLE
bug in my projet with the plugins

### ISSUE THREAD

**Issue by skyloRen** [yuessir/Nop.Plugin.ExternalAuth.NovellActiveDirectory#2]
bonjour, je suis étudiant et j'ai intégré votre plugins dans mon projet. j'obtient l'erreur suivant :

"plugins.externalauth.novellactivedirectory.ldaperror : system.argumentexception: invalid_address ---> system.formatexception: input string was not in a correct format. at system.number.stringtonumber(readonlyspan`1 str, numberstyles options, numberbuffer& number, numberformatinfo info, boolean parsedecimal) at system.number.parseint32(readonlyspan`1 s, numberstyles style, numberformatinfo info) at novell.directory.ldap.ldapconnection.connect(string host, int32 port) --- end of inner exception stack trace --- at novell.directory.ldap.ldapconnection.connect(string host, int32 port) at nop.plugin.externalauth.novellactivedirectory.services.ldapservice.getconnection() at nop.plugin.externalauth.novellactivedirectory.services.ldapservice.getuserbyusername(string username) at nop.plugin.externalauth.novellactivedirectory.controllers.novellactivedirectoryauthenticationcontroller.signin(signinviewmodel model, string returnurl) ".

 Auriez vous une idée pour régler ce problème ? je vous suis très reconnaisant du travaille que vous offrer en open source.

**Comment by yuessir** [comment]
_input string was not in a correct format._
Setting format like this
![0014700_active-directory-integration-ldap-integration](https://user-images.githubusercontent.com/8326310/146039835-618135f5-3457-431c-bd6e-9c4bc9f69f65.jpeg)

**Comment by skyloRen** [comment]
I thank you for your answer. I have one last question, to connect you must enter a username like cn = readonly, dc = example, dc = org? by what I have this error: 

"plugins.externalauth.novellactivedirectory.ldaperror: ldapexception: no such object (32) no such object ldapexception: matched dn:"

this is my config
![image](https://user-images.githubusercontent.com/95213026/146164674-9d7380c1-553d-4c99-8a12-71815b850b02.png)

**Comment by yuessir** [comment]
@skyloRen You have to check your company AD has the right object (ckeck the object of the LDAP path)

In my case, we use the Microsoft Active Directory , the tool https://docs.microsoft.com/en-us/sysinternals/downloads/adexplorer
It can help you check the object's path.

**Comment by skyloRen** [comment]
Hi, thanks for the link from microsoft. I tried but it doesn't work. I think that's what I'm using openldap and not active directory for. Is it possible to use your plugin with openldap? I send you screens of the configuration I made.

![Config](https://user-images.githubusercontent.com/95213026/146514203-c1c3a899-ab13-47e1-aa19-8d46bb8cdd47.PNG)

![Capture](https://user-images.githubusercontent.com/95213026/146514221-7dfc19eb-6fec-4162-b5b0-6b91a86ffd39.PNG)

![SignIn](https://user-images.githubusercontent.com/95213026/146514236-856f55d1-0f7f-4ba3-ae56-c91dff53f893.PNG)

**Comment by skyloRen** [comment]
I noticed with a breakpoint that the returnUrl parameter of the SignIn method was null. In the controller I have this error:
![error](https://user-images.githubusercontent.com/95213026/146518975-5e14fa26-15f5-41db-95ea-5edf59ba4fa9.PNG)

**Comment by yuessir** [comment]
> Hi, thanks for the link from microsoft. I tried but it doesn't work. I think that's what I'm using openldap and not active directory for. Is it possible to use your plugin with openldap? I send you screens of the configuration I made.
> 
> ![Config](https://user-images.githubusercontent.com/95213026/146514203-c1c3a899-ab13-47e1-aa19-8d46bb8cdd47.PNG)
> 
> ![Capture](https://user-images.githubusercontent.com/95213026/146514221-7dfc19eb-6fec-4162-b5b0-6b91a86ffd39.PNG)
> 
> ![SignIn](https://user-images.githubusercontent.com/95213026/146514236-856f55d1-0f7f-4ba3-ae56-c91dff53f893.PNG)
1.  In  config setting, **AD username** be set **admin** instad of cn=admin.... Here you need  an account with 
authorization. 
2. Try add one user with the property  `name`=UserTest


 This plugin  is customized for internal office. So some ladp property should be follow.
 In the code,  we use Ldap syntax filter likes
"(&(objectClass=user)(name={skyloRen}))";
That why you need to add a new property.

**Comment by skyloRen** [comment]
If I understood correctly, I need to create a user below NoProd which has the name = UserTest property? if so what class of object should you have? 

or otherwise I have to modify the filters in the source code like:
var filter = $"(&(objectClass=groupOfNames)(ou={groupName}))";
var filter = $"(&(objectClass=person)(cn={userName}))";

**Comment by yuessir** [comment]
> If I understood correctly, I need to create a user below NoProd which has the name = UserTest property? if so what class of object should you have?


`(&(objectClass=user)(name={skyloRen}))`

Ref
https://ldapwiki.com/wiki/User

**Comment by yuessir** [comment]
Yes the syntax is up to you. ;) 
(&(objectClass=user)(name={skyloRen}))

Ref
https://ldapwiki.com/wiki/User



Maybe you can pull request new feature to enhance the hard code defect. 👍

**Comment by skyloRen** [comment]
Ok, I will try to modify the source code as needed. I would just like to clarify the configuration of the plugins: if I want to connect with the user who has the Distinguished Name "cn = UserTest, ou = NoProd, dc = example, dc = org" I have to configure the ldap like this:

![config](https://user-images.githubusercontent.com/95213026/146554009-d5f8d1c3-b1b3-4d0d-868f-459f18304e23.PNG)

and I have to connect with the username below, is that correct?
After me to modify the filters in the source code 

![sign](https://user-images.githubusercontent.com/95213026/146554189-fa35b1b0-dc0f-467b-95ec-44f802d41ed5.PNG)

**Comment by skyloRen** [comment]
Yeeees it work. I thanks you so much for your help
